import assert from "node:assert/strict";
import { copyFileSync, mkdirSync, rmSync } from "node:fs";
import { chromium } from "playwright";

const base = process.env.WHYMARK_URL ?? "http://127.0.0.1:43917";
const out = process.env.WHYMARK_ARTIFACTS ?? "/tmp/whymark-improvements";
const fixture = "reviews/ui-improvements-fixture.whymark";
mkdirSync(out, { recursive: true });
copyFileSync("tests/fixtures/multiple-notes.whymark", fixture);
const browser = await chromium.launch();
try {
  const page = await browser.newPage({ viewport: { width: 1600, height: 1000 } });
  await page.goto(`${base}/r/ui-improvements-fixture`, { waitUntil: "networkidle" });
  const row = page.locator('[data-whymark-body="unified"] .whymark-row[data-notes~="security"]').first();
  const background = await row.evaluate(el => getComputedStyle(el).backgroundColor);
  await page.locator('#note-security').hover();
  await page.screenshot({ path: `${out}/hover.png` });
  assert.equal(await row.evaluate(el => getComputedStyle(el).backgroundColor), background, "security hover must preserve addition background");
  console.log("PASS semantic hover colors");
  assert.equal(await page.locator('#note-security button[aria-expanded]').getAttribute('aria-expanded'), 'false');
  assert.match(await page.locator('#note-security').innerText(), /urgent/);
  assert.match(await page.locator('#note-security').innerText(), /80% confidence/);
  await row.getByRole('button', { name: '3 comments on line 1' }).click();
  const chooser = page.getByRole('navigation', { name: 'Comments on selected line' });
  assert.equal(await chooser.getByRole('button').count(), 3);
  await chooser.getByRole('button', { name: /intent/ }).click();
  assert.equal(await page.locator('#note-intent button[aria-expanded]').getAttribute('aria-expanded'), 'true');
  await page.getByRole('button', { name: 'Collapse comment intent' }).click();
  assert.equal(await page.locator('#note-intent button[aria-expanded]').getAttribute('aria-expanded'), 'false');
  await page.getByRole('button', { name: 'Expand all', exact: true }).click();
  assert.equal(await page.locator('[aria-expanded="false"][aria-controls^="comment-body-"]').count(), 0);
  assert.equal(await page.locator('.whymark-gap').count(), 0);
  await page.waitForFunction(() => {
    const rects = [...document.querySelectorAll('section#file-0 [id^="note-"]')].map(card => card.getBoundingClientRect()).sort((a,b) => a.top-b.top);
    return rects.every((rect, i) => !i || rect.top >= rects[i-1].bottom - 1);
  });
  const overlap = await page.locator('section#file-0 [id^="note-"]').evaluateAll(cards => {
    const rects = cards.map(card => card.getBoundingClientRect()).sort((a, b) => a.top - b.top);
    return rects.some((rect, i) => i && rect.top < rects[i - 1].bottom - 1);
  });
  assert.equal(overlap, false, 'expanded cards must not overlap');
  await page.getByRole('button', { name: 'Collapse all', exact: true }).click();
  await page.getByRole('button', { name: /^intent\s*1$/ }).click();
  const filtered = page.locator('[data-whymark-body="unified"] .whymark-row[data-notes~="intent"]').first();
  assert.equal(await filtered.getAttribute('data-notes'), 'intent');
  await filtered.getByRole('button', { name: '1 comments on line 1' }).click();
  assert.equal(await page.locator('#note-intent button[aria-expanded]').getAttribute('aria-expanded'), 'true');
  await page.getByRole('button', { name: /^clear$/ }).click();
  console.log('PASS multiple comments, filtering, disclosure and compact layout');
  await page.getByRole('button', { name: /^split$/ }).click();
  const left = page.locator('[data-whymark-side="del"]').first();
  const right = page.locator('[data-whymark-side="add"]').first();
  await left.evaluate(el => { el.scrollLeft = 120; });
  await page.waitForTimeout(100);
  assert.equal(await right.evaluate(el => el.scrollLeft), 120);
  await right.evaluate(el => { el.scrollLeft = 60; });
  await page.waitForTimeout(100);
  assert.equal(await left.evaluate(el => el.scrollLeft), 60);
  const settings = page.getByRole('button', { name: 'Review settings', exact: true });
  await settings.click();
  await page.getByRole('checkbox', { name: 'Synchronize horizontal scrolling' }).uncheck();
  await page.keyboard.press('Escape');
  await page.waitForFunction(() => document.activeElement?.getAttribute('aria-label') === 'Review settings');
  assert.equal(await settings.evaluate(el => el === document.activeElement), true);
  await left.evaluate(el => { el.scrollLeft = 200; });
  await page.waitForTimeout(100);
  assert.equal(await right.evaluate(el => el.scrollLeft), 60);
  await settings.click();
  await page.getByRole('checkbox', { name: 'Synchronize horizontal scrolling' }).check();
  await page.keyboard.press('Escape');
  await page.waitForTimeout(100);
  assert.equal(await right.evaluate(el => el.scrollLeft), 200);
  const secondRight = page.locator('[data-whymark-side="add"]').nth(1);
  const secondLeft = page.locator('[data-whymark-side="del"]').nth(1);
  await secondRight.evaluate(el => { el.scrollLeft = 250; });
  await page.waitForTimeout(100);
  assert.equal(await secondLeft.evaluate(el => el.scrollLeft), 0);
  assert.equal(await secondRight.evaluate(el => el.scrollLeft), 250, 'short peer must not snap origin backwards');
  assert.equal(await right.evaluate(el => el.scrollLeft), 200, 'files must scroll independently');
  await page.screenshot({ path: `${out}/split.png` });
  await settings.click();
  await page.getByRole('checkbox', { name: 'Synchronize horizontal scrolling' }).uncheck();
  await page.keyboard.press('Escape');
  await page.reload({ waitUntil: 'networkidle' });
  await settings.click();
  assert.equal(await page.getByRole('checkbox', { name: 'Synchronize horizontal scrolling' }).isChecked(), false);
  await page.getByRole('button', { name: 'Reset defaults' }).click();
  await page.keyboard.press('Escape');
  console.log('PASS bidirectional split sync, setting, persistence and focus return');
  await page.setViewportSize({ width: 390, height: 844 });
  await page.waitForTimeout(300);
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true, 'no page overflow on narrow screens');
  assert.equal(await page.locator('#note-security').count(), 1);
  await page.screenshot({ path: `${out}/narrow.png` });
  await page.goto(`${base}/r/ui-improvements-fixture#note-intent`, { waitUntil: 'networkidle' });
  assert.equal(await page.locator('#note-intent button[aria-expanded]').getAttribute('aria-expanded'), 'true');
  console.log('PASS narrow layout and deep links');
  const blocked = await browser.newPage({ viewport: { width: 1600, height: 1000 } });
  await blocked.addInitScript(() => { Storage.prototype.setItem = () => { throw new DOMException('Quota exceeded', 'QuotaExceededError'); }; });
  await blocked.goto(`${base}/r/ui-improvements-fixture`, { waitUntil: 'networkidle' });
  await blocked.getByRole('button', { name: 'Review settings', exact: true }).click();
  await blocked.getByRole('checkbox', { name: 'Synchronize horizontal scrolling' }).uncheck();
  assert.equal(await blocked.getByRole('checkbox', { name: 'Synchronize horizontal scrolling' }).isChecked(), false);
  await blocked.keyboard.press('Escape');
  await blocked.getByRole('button', { name: 'Review settings', exact: true }).click();
  assert.equal(await blocked.getByRole('checkbox', { name: 'Synchronize horizontal scrolling' }).isChecked(), false);
  console.log('PASS storage write failure retains session preferences');
} finally {
  await browser.close();
  rmSync(fixture, { force: true });
}
