import * as vscode from "vscode";
import * as assert from "node:assert/strict";
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { execFileSync } from "node:child_process";
import type { activate } from "./extension";
const delay = (ms: number) => new Promise(resolve => setTimeout(resolve, ms));
export async function run() {
  const root = process.env.WHYMARK_TEST_ROOT!;
  const extension = vscode.extensions.getExtension<ReturnType<typeof activate>>("spink-dev.whymark");
  assert.ok(extension, "extension discovered");
  const api = await extension.activate();
  const latest = async () => {
    for (let i = 0; i < 100; i++) {
      const session = [...api.sessions].at(-1);
      if (session?.vm) return session;
      await delay(100);
    }
    throw new Error("Real webview did not load or send ready within 10 seconds.");
  };
  await vscode.commands.executeCommand("whymark.staged");
  const staged = await latest();
  assert.ok(staged.vm!.files[0].rows.some(r => r.kind === "add" && r.text.includes('"staged"')));
  assert.equal(staged.vm!.files[0].actionable, false, "index differs from disk; editing unavailable");
  await vscode.commands.executeCommand("whymark.unstaged");
  const unstaged = await latest();
  assert.notEqual(staged, unstaged);
  assert.ok(unstaged.vm!.files[0].rows.some(r => r.kind === "del" && r.text.includes('"staged"')));
  assert.ok(unstaged.vm!.files[0].rows.some(r => r.kind === "add" && r.text.includes('"unstaged"')));
  assert.equal(unstaged.vm!.files[0].actionable, true);
  const request = { type: "edit", id: 1, revision: unstaged.revision, path: "sample.ts", start: 1, end: 1, text: 'export const value = "edited";' };
  await assert.rejects(api.applyRequest(unstaged, { ...request, revision: 999 }), /review changed/);
  await assert.rejects(api.applyRequest(unstaged, { ...request, path: "../outside" }), /not part/);
  writeFileSync(join(root, "sample.ts"), "changed on disk\n");
  await assert.rejects(api.applyRequest(unstaged, request), /no longer matches/);
  writeFileSync(join(root, "sample.ts"), 'export const value = "unstaged";\n');
  const doc = await vscode.workspace.openTextDocument(vscode.Uri.file(join(root, "sample.ts")));
  const result = await api.applyRequest(unstaged, request);
  assert.equal(result.ok, true);
  assert.ok(doc.isDirty); assert.ok(doc.getText().includes('"edited"'));
  assert.ok(readFileSync(join(root, "sample.ts"), "utf8").includes('"unstaged"'), "disk untouched until save");
  assert.ok(execFileSync("git", ["show", ":sample.ts"], { cwd: root, encoding: "utf8" }).includes('"staged"'), "index untouched");
  await assert.rejects(api.applyRequest(unstaged, request), /unsaved/);
  await vscode.window.showTextDocument(doc);
  await vscode.commands.executeCommand("undo");
  assert.ok(doc.getText().includes('"unstaged"'), "native editor undo restores source");
  await assert.rejects(api.applyRequest(unstaged, { type: "apply", id: 2, revision: unstaged.revision, path: "sample.ts", decisions: { discardAdded: [99], restoreDeleted: [] } }), /changed lines/);
  await api.applyRequest(unstaged, { type: "apply", id: 3, revision: unstaged.revision, path: "sample.ts", decisions: { discardAdded: [1], restoreDeleted: [1] } });
  assert.ok(doc.getText().includes('"staged"'), "reject replaces added line with removed line");
  await vscode.window.showTextDocument(doc); await vscode.commands.executeCommand("undo");
  assert.ok(doc.getText().includes('"unstaged"'));
  const text = unstaged.text();
  const savedUri = vscode.Uri.file(join(root, "sample.whymark"));
  await api.saveReview(text, savedUri);
  assert.equal(readFileSync(savedUri.fsPath, "utf8"), text, "save creates exact review bytes");
  await assert.rejects(api.saveReview("overwrite", savedUri), /existing reviews/);
  assert.equal(readFileSync(savedUri.fsPath, "utf8"), text, "existing review is preserved");
  await vscode.commands.executeCommand("vscode.openWith", vscode.Uri.file(join(root, "sample.whymark")), "whymark.review");
  const saved = await latest();
  assert.equal(saved.vm!.files[0].path, "sample.ts");
  assert.ok(saved.document);
  const oldRevision = saved.revision;
  const edit = new vscode.WorkspaceEdit(); edit.insert(saved.document.uri, new vscode.Position(0, 0), "\n");
  await vscode.workspace.applyEdit(edit);
  for (let i = 0; i < 50 && saved.revision === oldRevision; i++) await delay(100);
  assert.ok(saved.revision > oldRevision, "raw editor changes refresh custom editor");
  console.log("WHYMARK: real extension host checks passed (activation, webview ready, staged/unstaged, stale and dirty guards, undo, index safety, custom editor refresh)");
  await vscode.workspace.saveAll();
  for (const session of api.sessions) session.panel.dispose();
}
